-- TABLESPACE FORNECEDOR
CREATE TABLESPACE TBS_FORNECEDOR
DATAFILE 'C:\Users\dudu\Desktop\projetos\AutonomoDatabase\BD_CentroDistribuicao\TABLESPACES\oradata_fornecedor\fornecedor.dbf' SIZE 100M
AUTOEXTEND ON
NEXT 10M
MAXSIZE 256M
EXTENT MANAGEMENT LOCAL UNIFORM SIZE 1M;

-- TABLESPACE FILIAL
CREATE TABLESPACE TBS_FILIAL
DATAFILE 'C:\Users\dudu\Desktop\projetos\AutonomoDatabase\BD_CentroDistribuicao\TABLESPACES\oradata_filial\filial.dbf' SIZE 100M
AUTOEXTEND ON
NEXT 10M
MAXSIZE 256M
EXTENT MANAGEMENT LOCAL UNIFORM SIZE 1M;
